
###
## Conduct simple comparison between stocks and fluxes for the scenario analysis
## Comparison at this point is against median estimates only.
### 

scenario_comparison<-function(PROJECT) {

  # loop through each site
  for (n in seq(1, PROJECT$nosites)) {

      ###
      ## Find the reference analysis (that generated by stage = 3)
      outfile=paste(PROJECT$results_processedpath,PROJECT$sites[n],".RData",sep="")
      
      if (file.exists(outfile)) {

	  ###
	  ## Load and assign the reference analysis, generate the needed timing information

	  # Read in the reference material
	  load(outfile)
	  # pass reference analysis to a new object information to a new 
	  reference = states_all ; reference_drivers = drivers ; reference_parameters = parameters

	  # calculate some timing information
	  timestep=1
	  if (PROJECT$model$timestep == "monthly") {timestep=mean(PROJECT$model$timestep_days)}
	  if (PROJECT$model$timestep == "weekly") {timestep=mean(PROJECT$model$timestep_days)}
	  time_vector=1:dim(states_all$gpp)[2]
	  year_vector=time_vector/(365.25/timestep)
	  year_vector=year_vector+as.numeric(PROJECT$start_year)
	  interval=floor(length(year_vector)/10)

	  ###
	  ## Determine how many comparisons available
	  # list all files in the directory
	  list_of_files = list.files(PROJECT$results_processedpath)
	  # check we only have *RData files in there
	  filter = grepl("RData",list_of_files)
	  list_of_files = list_of_files[filter]
	  # Remove any parameter only files 
	  filter = grepl("parameter",list_of_files)
	  list_of_files = list_of_files[filter == FALSE]
	  # Remove the reference analysis
	  filter = grepl(paste(PROJECT$sites[n],".RData",sep=""),list_of_files)
	  list_of_files = list_of_files[filter == FALSE]

	  # Total number of comparisons
	  nos_comparisons = length(list_of_files)
	  # loop through the available scenarios and add them to a list object for later use
	  for (c in seq(1,nos_comparisons)) {
	      altfile=paste(PROJECT$results_processedpath,list_of_files[c],sep="")
	      load(altfile)
	      # either create a list into which we will place all of the scenarios or append it to the existing list
	      if (c == 1) { 
		  scenario = list(states_all)
	      } else { 
		  scenario[[c]] = states_all
	      }

	  } # loop through and read in the scenario files
  
	  # select some nice colours to use for each scenario but keeping our reference as "blue", as that it what is used by default elsewhere
	  colour_choices_function = colorRampPalette((brewer.pal(10,"Spectral")))
	  colour_choices=colour_choices_function(nos_comparisons)

	  ###
	  ## Do comparison of wood stocks between scenarios
	  ## Please see names(reference) for other variables
	  ## and "uncertainty_figures.r" for other plotting examples

	  # structure needed by function is dim=c(time,iter) but provided in dim=c(iter,time)
	  # flip it to get the right shape
	  Cw_var=t(reference$wood)
	  # NOTE: that you can see the other variables by typing names(reference)

	  # pass observations driver
	  Cwood_obs=reference_drivers$obs[,7] ; Cwood_obs_unc=reference_drivers$obs[,18]
	  # filter -9999 to NA
	  filter = which(Cwood_obs == -9999) ; Cwood_obs[filter] = NA ; Cwood_obs_unc[filter] = NA

	  jpeg(file=paste(PROJECT$figpath,"scenario_timeseries_Cwood_",PROJECT$sites[n],"_",PROJECT$name,".jpg",sep=""), width=7200, height=4000, res=300, quality=100)
	  # now create the plotting area
	  par(mfrow=c(1,1), mar=c(5,5,3,1))
	  plot(rep(-9999,dim(Cw_var)[1]),xaxt="n", pch=16, ylim=c(0,quantile(as.vector(Cw_var), prob=c(0.999), na.rm=TRUE)), cex=0.8,ylab="Cwood (gC.m-2)",xlab="Time (Year)", cex.lab=1.8, cex.axis=1.8, cex.main=1.8, main=paste(PROJECT$sites[n]," - ",PROJECT$name, sep=""))
	  axis(1, at=time_vector[seq(1,length(time_vector),interval)],labels=round(year_vector[seq(1,length(time_vector),interval)], digits=0),tck=-0.02, padj=+0.15, cex.axis=1.9)
	  # add the confidence intervals for the reference analysis
	  plotconfidence(Cw_var)
	  ## draw the scenario median estimates first
	  for (c in seq(1,nos_comparisons)) {lines(apply(scenario[[c]]$wood[,1:(dim(Cw_var)[1]-1)],2,median,na.rm=TRUE), lwd=2.5, col=colour_choices[c])}
	  # calculate and draw the median values for the reference,
	  lines(apply(Cw_var[1:(dim(Cw_var)[1]-1),],1,median,na.rm=TRUE), lwd=1, col="blue")
	  # add the data on top if there is any
	  if (length(which(is.na(Cwood_obs))) != length(Cwood_obs) ) {
	      points(Cwood_obs, pch=16, cex=0.8)
	      plotCI(Cwood_obs,gap=0,uiw=Cwood_obs*Cwood_obs_unc, col="black", add=TRUE, cex=1,lwd=2,sfrac=0.01,lty=1,pch=16)
	  }
	  dev.off()

      } # if reference file exists

  } # site loop

} # end function

